# This is a basic workflow to help you get started with Actions

name: Deploy to documents

# Controls when the action will run.
on:
  push:
    branches:
      - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy-documents:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # node version
    strategy:
      matrix:
        node-version: ['14.19']

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # deploy to github page
      - name: deploy to github page
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          allow_empty_commit: true
